# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='adsl ip', max_length=100)),
                ('interface', models.CharField(help_text='\u7f51\u53e3\u4fe1\u606f', max_length=100)),
                ('up_total', models.IntegerField(help_text='\u4e0a\u884c\u6700\u5927\u5e26\u5bbd')),
                ('download_total', models.IntegerField(help_text='\u4e0b\u884c\u6700\u5927\u5e26\u5bbd')),
            ],
        ),
        migrations.AlterField(
            model_name='notify',
            name='content',
            field=models.CharField(help_text='\u663e\u793a\u5728\u9875\u9762\u7684\u901a\u77e5\u4fe1\u606f', max_length=200),
        ),
    ]
