# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsl', '0002_auto_20160906_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='equrrdment',
            field=models.CharField(blank=True, help_text='\u8bbe\u5907\u7c7b\u578b\uff0c\u5982ADSL\uff0c\u5149\u7ea4', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='purpose',
            field=models.CharField(blank=True, help_text='\u7528\u9014\uff0c\u5982\u7f51\u7ad9', max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='info',
            table='info',
        ),
        migrations.AlterModelTable(
            name='notify',
            table='notify',
        ),
    ]
