# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsl', '0003_auto_20160906_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='download_total',
            new_name='down_total',
        ),
    ]
